kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: appstudio
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
