resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/dirgim/integration-service/config/default?ref=ff0424160abdf380d0e5df4977ee4f58511b70b9
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/kpavic/integration-service
    newTag: latest
namespace: integration-service
patches:
  - ./manager_resources_patch.yaml
